make --enable-filters option work
Filter classes have a mandatory argument.  Trying to use the
--enable-filters would result in:

    TypeError: __init__() takes exactly 2 arguments (1 given)

Because the code did not pass a value for 'database'.