MeFilter: generalize init function
Instead of accepting only tags_blacklist just pass everything but
me_tags to the super class's init function. This way the message can be
overwritten in the config which up to now yields an exception:

	TypeError: __init__() got an unexpected keyword argument 'message'